### PR TITLE
Simultaneous horizontal  and  vertical scrolling

### PR DESCRIPTION
**Pull request by fvalverd**
See examples/vertical_and_horizontal.html

### CODE REVIEW

**Comment by warlockdn** [comment]
Not able to find the horizontal scroll file. Does it support horizontal and vertical scroll both now ?

**Comment by lanre-ade** [comment]
I stumbled across this but had a lot of issues getting it to work properly. I ended up making a fork of the original repo and adding simultaneous support for horizontal and vertical scrollbars
Here it is, if anyone is interested
https://github.com/lanre-ade/jQuery-slimScroll

**Comment by iamsarav** [comment]
is there any online demo for horizontal scrollbar?

**Comment by ninpen** [comment]
The example is missing. Can you please repost it

**Pull request closed without merging**
