### PR TITLE
add bower.son bump up version

### PR DESCRIPTION
**Pull request by ck-developer**
http://bower.io/docs/creating-packages/

### CODE REVIEW

**Comment by rochal** [comment]
Why not stick with npm?

**Comment by ck-developer** [comment]
just more choice ! personally I use bower to manage frontend dependencies !?

**Comment by saeidzebardast** [comment]
+1 for bower.json

**Comment by saeidzebardast** [comment]
_bower.json_ (bower component) helps to wiredep (inject dependencies);

**Comment by rochal** [comment]
sure, if people really use it, added it back in.

**Comment by saeidzebardast** [comment]
Thanks :+1:

**Pull request merged**
